// <auto-generated />
using System;
using ApiPoo2.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ApiPoo2.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20261001052257_RemoveShadowForeignKeys")]
    partial class RemoveShadowForeignKeys
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ApiPoo2.Domain.BlacklistedTokens.BlacklistedToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at_utc");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("timestamptz")
                        .HasColumnName("expires_at_utc");

                    b.Property<Guid>("Jti")
                        .HasColumnType("uuid")
                        .HasColumnName("jti");

                    b.Property<Guid>("PersonaId")
                        .HasColumnType("uuid")
                        .HasColumnName("idpersona");

                    b.Property<DateTime>("RevokedAtUtc")
                        .HasColumnType("timestamptz")
                        .HasColumnName("revoked_at_utc");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAtUtc");

                    b.HasIndex("Jti")
                        .IsUnique();

                    b.ToTable("access_token_blacklist", (string)null);
                });

            modelBuilder.Entity("ApiPoo2.Domain.Documentos.Documento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("codigo");

                    b.Property<string>("CodigoObligatoriedad")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("codigo_obligatoriedad");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("descripcion");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombre");

                    b.Property<string>("TiposVehiculoAplicables")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("tipos_vehiculo_aplicables");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.ToTable("documentos", null, t =>
                        {
                            t.HasCheckConstraint("ck_documentos_codigo_obligatoriedad", "codigo_obligatoriedad IN ('RA','RM','RR')");

                            t.HasCheckConstraint("ck_documentos_tipos_vehiculo_aplicables", "tipos_vehiculo_aplicables IN ('A','M','AM')");
                        });
                });

            modelBuilder.Entity("ApiPoo2.Domain.Documentos.VehiculoDocumento", b =>
                {
                    b.Property<Guid>("VehiculoId")
                        .HasColumnType("uuid")
                        .HasColumnName("idvehiculo");

                    b.Property<Guid>("DocumentoId")
                        .HasColumnType("uuid")
                        .HasColumnName("iddocumento");

                    b.Property<byte[]>("Contenido")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("contenido");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("estado");

                    b.Property<DateTime>("FechaExpedicion")
                        .HasColumnType("timestamptz")
                        .HasColumnName("fecha_expedicion");

                    b.Property<DateTime>("FechaVencimiento")
                        .HasColumnType("timestamptz")
                        .HasColumnName("fecha_vencimiento");

                    b.Property<string>("NombreArchivo")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("nombre_archivo");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("VehiculoId", "DocumentoId");

                    b.HasIndex("DocumentoId");

                    b.ToTable("vehiculos_documentos", null, t =>
                        {
                            t.HasCheckConstraint("ck_vehiculos_documentos_contenido", "octet_length(contenido) > 0");

                            t.HasCheckConstraint("ck_vehiculos_documentos_estado", "estado IN ('HABILITADO','VENCIDO','EN_VERIFICACION')");
                        });
                });

            modelBuilder.Entity("ApiPoo2.Domain.Personas.ConductorVehiculo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("estado");

                    b.Property<DateTime>("FechaAsociacion")
                        .HasColumnType("timestamptz")
                        .HasColumnName("fecha_asociacion");

                    b.Property<Guid>("PersonaId")
                        .HasColumnType("uuid")
                        .HasColumnName("idpersona");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at_utc");

                    b.Property<Guid>("VehiculoId")
                        .HasColumnType("uuid")
                        .HasColumnName("idvehiculo");

                    b.HasKey("Id");

                    b.HasIndex("VehiculoId");

                    b.HasIndex("PersonaId", "VehiculoId")
                        .IsUnique();

                    b.ToTable("conductores_vehiculos", null, t =>
                        {
                            t.HasCheckConstraint("ck_conductores_vehiculos_estado", "estado IN ('PO','EA','RO')");
                        });
                });

            modelBuilder.Entity("ApiPoo2.Domain.Personas.Persona", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("apellidos");

                    b.Property<string>("CorreoElectronico")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("correo_electronico");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Nombres")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombres");

                    b.Property<string>("NumeroIdentificacion")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("numero_identificacion");

                    b.Property<string>("TipoIdentificacion")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("tipo_identificacion");

                    b.Property<string>("TipoPersona")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("tipo_persona");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id");

                    b.HasIndex("CorreoElectronico")
                        .IsUnique();

                    b.HasIndex("NumeroIdentificacion")
                        .IsUnique();

                    b.HasIndex("TipoPersona");

                    b.ToTable("personas", null, t =>
                        {
                            t.HasCheckConstraint("ck_personas_correo", "correo_electronico ~ '^[^@]+@[^@]+\\.[^@]+$'");

                            t.HasCheckConstraint("ck_personas_num_identificacion", "numero_identificacion ~ '^[0-9]+$'");

                            t.HasCheckConstraint("ck_personas_tipo_identificacion", "tipo_identificacion IN ('CC','CE','TI','NIT')");

                            t.HasCheckConstraint("ck_personas_tipo_persona", "tipo_persona IN ('ADMINISTRATIVO','CONDUCTOR')");
                        });
                });

            modelBuilder.Entity("ApiPoo2.Domain.RefreshTokens.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at_utc");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("timestamptz")
                        .HasColumnName("expires_at_utc");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("boolean")
                        .HasColumnName("is_revoked");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("boolean")
                        .HasColumnName("is_used");

                    b.Property<Guid?>("ReplacedByTokenId")
                        .HasColumnType("uuid")
                        .HasColumnName("replaced_by_token_id");

                    b.Property<DateTime?>("RevokedAtUtc")
                        .HasColumnType("timestamptz")
                        .HasColumnName("revoked_at_utc");

                    b.Property<string>("RevokedReason")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("revoked_reason");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("token_hash");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at_utc");

                    b.Property<DateTime?>("UsedAtUtc")
                        .HasColumnType("timestamptz")
                        .HasColumnName("used_at_utc");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("idpersona");

                    b.Property<string>("UserLogin")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("login");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAtUtc");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("UserId", "UserLogin");

                    b.ToTable("refresh_tokens", (string)null);
                });

            modelBuilder.Entity("ApiPoo2.Domain.Users.User", b =>
                {
                    b.Property<Guid>("IdPersona")
                        .HasColumnType("uuid")
                        .HasColumnName("idpersona");

                    b.Property<string>("Login")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("login");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer")
                        .HasColumnName("access_failed_count");

                    b.Property<string>("ApiKey")
                        .IsRequired()
                        .HasMaxLength(96)
                        .HasColumnType("character varying(96)")
                        .HasColumnName("api_key");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at_utc");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<DateTime?>("LastLoginAtUtc")
                        .HasColumnType("timestamptz")
                        .HasColumnName("last_login_at_utc");

                    b.Property<DateTimeOffset?>("LockoutEndUtc")
                        .HasColumnType("timestamptz")
                        .HasColumnName("lockout_end_utc");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("password_hash");

                    b.Property<string>("PasswordHashAlgorithm")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("password_hash_algorithm");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("rol");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("IdPersona", "Login");

                    b.HasIndex("ApiKey")
                        .IsUnique();

                    b.HasIndex("IdPersona")
                        .IsUnique();

                    b.HasIndex("Login");

                    b.HasIndex("IdPersona", "ApiKey");

                    b.ToTable("usuarios", (string)null);
                });

            modelBuilder.Entity("ApiPoo2.Domain.Vehiculos.Vehiculo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("CapacidadPasajeros")
                        .HasColumnType("integer")
                        .HasColumnName("capacidad_pasajeros");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)")
                        .HasColumnName("color");

                    b.Property<string>("Combustible")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("tipo_combustible");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Linea")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("linea");

                    b.Property<string>("Marca")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("marca");

                    b.Property<int>("Modelo")
                        .HasColumnType("integer")
                        .HasColumnName("modelo");

                    b.Property<string>("Placa")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("placa");

                    b.Property<string>("TipoServicio")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("tipo_servicio");

                    b.Property<string>("TipoVehiculo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("tipo_vehiculo");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id");

                    b.HasIndex("Placa")
                        .IsUnique();

                    b.HasIndex("TipoVehiculo");

                    b.ToTable("vehiculos", null, t =>
                        {
                            t.HasCheckConstraint("ck_vehiculos_capacidad_pasajeros", "capacidad_pasajeros >= 0");

                            t.HasCheckConstraint("ck_vehiculos_color", "color ~ '^#[0-9A-Fa-f]{6}$'");

                            t.HasCheckConstraint("ck_vehiculos_modelo", "modelo > 0");

                            t.HasCheckConstraint("ck_vehiculos_placa", "(tipo_vehiculo = 'AUTOMOVIL' AND placa ~ '^[A-Z]{3}[0-9]{3}$') OR (tipo_vehiculo = 'MOTOCIClETA' AND placa ~ '^[A-Z]{3}[0-9]{2}[A-Z]$')");

                            t.HasCheckConstraint("ck_vehiculos_tipo_combustible", "tipo_combustible IN ('GASOLINA','GAS','DISEL')");

                            t.HasCheckConstraint("ck_vehiculos_tipo_servicio", "tipo_servicio IN ('PUBLICO','PRIVADO')");

                            t.HasCheckConstraint("ck_vehiculos_tipo_vehiculo", "tipo_vehiculo IN ('AUTOMOVIL','MOTOCIClETA')");
                        });
                });

            modelBuilder.Entity("ApiPoo2.Domain.Documentos.VehiculoDocumento", b =>
                {
                    b.HasOne("ApiPoo2.Domain.Documentos.Documento", null)
                        .WithMany()
                        .HasForeignKey("DocumentoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ApiPoo2.Domain.Vehiculos.Vehiculo", null)
                        .WithMany("DocumentosAssociated")
                        .HasForeignKey("VehiculoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ApiPoo2.Domain.Personas.ConductorVehiculo", b =>
                {
                    b.HasOne("ApiPoo2.Domain.Personas.Persona", "Persona")
                        .WithMany("ConductoresVehiculosAssociated")
                        .HasForeignKey("PersonaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ApiPoo2.Domain.Vehiculos.Vehiculo", null)
                        .WithMany("ConductoresAssociated")
                        .HasForeignKey("VehiculoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Persona");
                });

            modelBuilder.Entity("ApiPoo2.Domain.RefreshTokens.RefreshToken", b =>
                {
                    b.HasOne("ApiPoo2.Domain.Users.User", null)
                        .WithMany("RefreshTokensVisibles")
                        .HasForeignKey("UserId", "UserLogin")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ApiPoo2.Domain.Users.User", b =>
                {
                    b.HasOne("ApiPoo2.Domain.Personas.Persona", null)
                        .WithOne("Usuario")
                        .HasForeignKey("ApiPoo2.Domain.Users.User", "IdPersona")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ApiPoo2.Domain.Personas.Persona", b =>
                {
                    b.Navigation("ConductoresVehiculosAssociated");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("ApiPoo2.Domain.Users.User", b =>
                {
                    b.Navigation("RefreshTokensVisibles");
                });

            modelBuilder.Entity("ApiPoo2.Domain.Vehiculos.Vehiculo", b =>
                {
                    b.Navigation("ConductoresAssociated");

                    b.Navigation("DocumentosAssociated");
                });
#pragma warning restore 612, 618
        }
    }
}
